using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Adbc.Drivers.Build.Acquisition;
using Adbc.Drivers.Build.Text;

namespace Adbc.Drivers.Build.Packaging
{
    /// <summary>
    /// Writes ADBC runtime driver manifests describing deployed drivers.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>Driver.shared</c> is required by the ADBC manifest specification and must name
    /// the shared library. It may be relative, in which case the ADBC .NET driver manager
    /// resolves it against the <em>manifest's own directory</em> and requires the result
    /// to remain within that directory. Relative paths are therefore the default here:
    /// they survive relocation, which matters because a published application is normally
    /// deployed somewhere unrelated to the publish directory on the build agent.
    /// </para>
    /// <para>
    /// Absolute paths remain available for driver managers that require them, and are
    /// why manifests are generated per destination rather than copied out of the cache.
    /// In that mode a manifest is valid only for the directory it was generated into, so
    /// moving a published folder invalidates it.
    /// </para>
    /// <para>
    /// In relative mode the generated content does not depend on the destination at all,
    /// so the build and publish manifests are byte-identical.
    /// </para>
    /// </remarks>
    internal static class RuntimeManifestGenerator
    {
        private const string Header =
            "Generated by Adbc.Drivers.Build. Do not edit.\n"
            + "Paths below are relative to this directory unless absolute.";

        /// <summary>
        /// Written to the manifest's <c>source</c> field, which the ADBC manifest format
        /// defines as where the driver came from. Surfaced by
        /// <c>DriverManifest.Source</c>, so a deployed driver can say what produced it
        /// without anyone having to consult the build.
        /// </summary>
        private const string GeneratorName = "Adbc.Drivers.Build";

        /// <summary>
        /// Writes one manifest per driver into <paramref name="outputDirectory"/>, with
        /// paths that point at the corresponding files under <paramref name="deploymentRoot"/>.
        /// </summary>
        /// <param name="deploymentRoot">
        /// The deployed <c>adbc</c> directory the manifest should point into. For a build
        /// this is <c>$(TargetDir)adbc</c>; for a publish, <c>$(PublishDir)adbc</c>.
        /// </param>
        /// <param name="outputDirectory">
        /// Where to write the <c>.toml</c> files. Usually the same as
        /// <paramref name="deploymentRoot"/>, but publish stages them elsewhere first.
        /// </param>
        /// <param name="useRelativePaths">
        /// Emit paths relative to the manifest instead of absolute ones. Off by default,
        /// because ADBC driver managers reject relative shared-library paths unless
        /// explicitly configured to allow them.
        /// </param>
        /// <returns>The absolute path of each manifest written.</returns>
        public static IReadOnlyList<string> Generate(
            DeploymentPlan plan,
            string deploymentRoot,
            string outputDirectory,
            bool useRelativePaths)
        {
            if (plan is null) throw new ArgumentNullException(nameof(plan));
            if (deploymentRoot is null) throw new ArgumentNullException(nameof(deploymentRoot));
            if (outputDirectory is null) throw new ArgumentNullException(nameof(outputDirectory));

            string root = Path.GetFullPath(deploymentRoot);
            string output = Path.GetFullPath(outputDirectory);
            Directory.CreateDirectory(output);

            List<string> written = new List<string>();
            HashSet<string> usedNames = new HashSet<string>(Util.PathSafety.PathComparer);

            foreach (DeployedDriver driver in plan.Drivers)
            {
                string fileName = driver.ManifestName + ".toml";
                if (!usedNames.Add(fileName))
                {
                    throw new PackageManifestException(
                        $"More than one driver would be written to the manifest '{fileName}'. Set distinct ManifestName metadata on the AdbcDriver items.");
                }

                string path = Path.Combine(output, fileName);
                string text = Build(driver, root, useRelativePaths);

                // Only rewrite on change, so the file's timestamp does not defeat
                // incremental copies downstream.
                if (!File.Exists(path) || !string.Equals(File.ReadAllText(path, Encoding.UTF8), text, StringComparison.Ordinal))
                {
                    File.WriteAllText(path, text, new UTF8Encoding(false));
                }

                written.Add(path);
            }

            return written;
        }

        internal static string Build(DeployedDriver driver, string deploymentRoot, bool useRelativePaths)
        {
            TomlTable root = new TomlTable();
            root.SetString("manifest_version", "1");

            if (!string.IsNullOrWhiteSpace(driver.Name))
            {
                root.SetString("name", driver.Name!);
            }

            root.SetString("version", driver.Version);

            if (!string.IsNullOrWhiteSpace(driver.Publisher))
            {
                root.SetString("publisher", driver.Publisher!);
            }

            if (!string.IsNullOrWhiteSpace(driver.License))
            {
                root.SetString("license", driver.License!);
            }

            root.SetString("source", GeneratorName);

            if (!string.IsNullOrWhiteSpace(driver.AdbcVersion))
            {
                root.GetOrAddTable("ADBC").SetString("version", NormalizeAdbcVersion(driver.AdbcVersion!));
            }

            // Only written when actually known. Guessing "AdbcDriverInit" for an archive
            // that did not declare an entrypoint would override the driver manager's own
            // default resolution and could name a symbol the library does not export.
            if (!string.IsNullOrWhiteSpace(driver.Entrypoint))
            {
                root.GetOrAddTable("Driver").SetString("entrypoint", driver.Entrypoint!);
            }

            TomlTable shared = root.GetOrAddTablePath("Driver", "shared");
            foreach (DeployedArtifact artifact in driver.Artifacts)
            {
                string value = useRelativePaths
                    ? artifact.RelativeDriverPath
                    : Path.Combine(deploymentRoot, artifact.RelativeDriverPath.Replace('/', Path.DirectorySeparatorChar));
                shared.SetString(artifact.AdbcPlatform, value);
            }

            return TomlWriter.Write(root, Header);
        }

        /// <summary>
        /// Archives spell the ADBC version with a <c>v</c> prefix; the manifest format
        /// does not use one.
        /// </summary>
        private static string NormalizeAdbcVersion(string version)
        {
            string trimmed = version.Trim();
            return trimmed.Length > 1 && (trimmed[0] == 'v' || trimmed[0] == 'V')
                ? trimmed.Substring(1)
                : trimmed;
        }
    }
}
